const tempBooks: Book[] =
  [{
    "id": "1",
    "title": "The Hunger Games",
    "authorId": "real_author_de951c10d9",
    "author": "Suzanne Collins",
    "genre": "Dystopian",
    "description": "Popular dystopian book by Suzanne Collins. Added to the catalog as real metadata for the recommendation web application.",
    "year": 2008,
    "averageRating": 3.44,
    "ratingsCount": 9,
    "readCount": 5,
    "reviewCount": 5,
    "goodreadsUrl": "https://www.goodreads.com/search?q=The+Hunger+Games+Suzanne+Collins",
    "coverUrl": "",
  },
  {
    "id": "2",
    "title": "Harry Potter and the Sorcerer's Stone",
    "authorId": "real_author_c134b8caf4",
    "author": "J.K. Rowling",
    "genre": "Fantasy",
    "description": "Popular fantasy book by J.K. Rowling. Added to the catalog as real metadata for the recommendation web application.",
    "year": 1997,
    "averageRating": 3.0,
    "ratingsCount": 2,
    "readCount": 2,
    "reviewCount": 2,
    "goodreadsUrl": "https://www.goodreads.com/search?q=Harry+Potter+and+the+Sorcerer%27s+Stone+J.K.+Rowling",
    "coverUrl": "",
  },
  {
    "id": "3",
    "title": "Twilight",
    "authorId": "real_author_6360595944",
    "author": "Stephenie Meyer",
    "genre": "Romance",
    "description": "Popular romance book by Stephenie Meyer. Added to the catalog as real metadata for the recommendation web application.",
    "year": 2005,
    "averageRating": 3.89,
    "ratingsCount": 9,
    "readCount": 8,
    "reviewCount": 8,
    "goodreadsUrl": "https://www.goodreads.com/search?q=Twilight+Stephenie+Meyer",
    "coverUrl": "",
  },
  {
    "id": "4",
    "title": "To Kill a Mockingbird",
    "authorId": "real_author_5638ca3f23",
    "author": "Harper Lee",
    "genre": "Classic",
    "description": "Popular classic book by Harper Lee. Added to the catalog as real metadata for the recommendation web application.",
    "year": 1960,
    "averageRating": 4.0,
    "ratingsCount": 3,
    "readCount": 2,
    "reviewCount": 3,
    "goodreadsUrl": "https://www.goodreads.com/search?q=To+Kill+a+Mockingbird+Harper+Lee",
    "coverUrl": "",
  },
  {
    "id": "5",
    "title": "The Great Gatsby",
    "authorId": "real_author_f81f9ed61a",
    "author": "F. Scott Fitzgerald",
    "genre": "Classic",
    "description": "Popular classic book by F. Scott Fitzgerald. Added to the catalog as real metadata for the recommendation web application.",
    "year": 1925,
    "averageRating": 4.25,
    "ratingsCount": 4,
    "readCount": 3,
    "reviewCount": 3,
    "goodreadsUrl": "https://www.goodreads.com/search?q=The+Great+Gatsby+F.+Scott+Fitzgerald",
    "coverUrl": "",
  },
{
    "id": "6",
    "title": "The Fault in Our Stars",
    "authorId": "real_author_cd6b65b55b",
    "author": "John Green",
    "genre": "Romance",
    "description": "Popular romance book by John Green. Added to the catalog as real metadata for the recommendation web application.",
    "year": 2012,
    "averageRating": 4.2,
    "ratingsCount": 10,
    "readCount": 9,
    "reviewCount": 6,
    "goodreadsUrl": "https://www.goodreads.com/search?q=The+Fault+in+Our+Stars+John+Green",
    "coverUrl": "",
  },
  {
    "id": "7",
    "title": "The Hobbit",
    "authorId": "real_author_c0bb56a4dd",
    "author": "J.R.R. Tolkien",
    "genre": "Fantasy",
    "description": "Popular fantasy book by J.R.R. Tolkien. Added to the catalog as real metadata for the recommendation web application.",
    "year": 1937,
    "averageRating": 4.6,
    "ratingsCount": 5,
    "readCount": 5,
    "reviewCount": 4,
    "goodreadsUrl": "https://www.goodreads.com/search?q=The+Hobbit+J.R.R.+Tolkien",
    "coverUrl": "",
  },
  {
    "id": "8",
    "title": "The Catcher in the Rye",
    "authorId": "real_author_6631e9f3b7",
    "author": "J.D. Salinger",
    "genre": "Classic",
    "description": "Popular classic book by J.D. Salinger. Added to the catalog as real metadata for the recommendation web application.",
    "year": 1951,
    "averageRating": 4.67,
    "ratingsCount": 3,
    "readCount": 3,
    "reviewCount": 1,
    "goodreadsUrl": "https://www.goodreads.com/search?q=The+Catcher+in+the+Rye+J.D.+Salinger",
    "coverUrl": "",
  },
  {
    "id": "9",
    "title": "Angels & Demons",
    "authorId": "real_author_de6dc0b346",
    "author": "Dan Brown",
    "genre": "Thriller",
    "description": "Popular thriller book by Dan Brown. Added to the catalog as real metadata for the recommendation web application.",
    "year": 2000,
    "averageRating": 4.0,
    "ratingsCount": 7,
    "readCount": 7,
    "reviewCount": 3,
    "goodreadsUrl": "https://www.goodreads.com/search?q=Angels+%26+Demons+Dan+Brown",
    "coverUrl": "",
  },
  {
    "id": "10",
    "title": "Pride and Prejudice",
    "authorId": "real_author_3af5e3fc71",
    "author": "Jane Austen",
    "genre": "Classic",
    "description": "Popular classic book by Jane Austen. Added to the catalog as real metadata for the recommendation web application.",
    "year": 1813,
    "averageRating": 0.0,
    "ratingsCount": 0,
    "readCount": 0,
    "reviewCount": 0,
    "goodreadsUrl": "https://www.goodreads.com/search?q=Pride+and+Prejudice+Jane+Austen",
    "coverUrl": "",
  },
  {
    "id": "11",
    "title": "The Kite Runner",
    "authorId": "real_author_e46f7506a4",
    "author": "Khaled Hosseini",
    "genre": "Historical Fiction",
    "description": "Popular historical fiction book by Khaled Hosseini. Added to the catalog as real metadata for the recommendation web application.",
    "year": 2003,
    "averageRating": 4.25,
    "ratingsCount": 8,
    "readCount": 7,
    "reviewCount": 6,
    "goodreadsUrl": "https://www.goodreads.com/search?q=The+Kite+Runner+Khaled+Hosseini",
    "coverUrl": "",
  },
  {
    "id": "12",
    "title": "Divergent",
    "authorId": "real_author_8df71167b2",
    "author": "Veronica Roth",
    "genre": "Dystopian",
    "description": "Popular dystopian book by Veronica Roth. Added to the catalog as real metadata for the recommendation web application.",
    "year": 2011,
    "averageRating": 4.12,
    "ratingsCount": 8,
    "readCount": 8,
    "reviewCount": 3,
    "goodreadsUrl": "https://www.goodreads.com/search?q=Divergent+Veronica+Roth",
    "coverUrl": "",
  },
  {
    "id": "13",
    "title": "1984",
    "authorId": "real_author_8e6d6235e8",
    "author": "George Orwell",
    "genre": "Dystopian",
    "description": "Popular dystopian book by George Orwell. Added to the catalog as real metadata for the recommendation web application.",
    "year": 1949,
    "averageRating": 3.67,
    "ratingsCount": 12,
    "readCount": 10,
    "reviewCount": 7,
    "goodreadsUrl": "https://www.goodreads.com/search?q=1984+George+Orwell",
    "coverUrl": "",
  },
  {
    "id": "14",
    "title": "Animal Farm",
    "authorId": "real_author_8e6d6235e8",
    "author": "George Orwell",
    "genre": "Classic",
    "description": "Popular classic book by George Orwell. Added to the catalog as real metadata for the recommendation web application.",
    "year": 1945,
    "averageRating": 3.67,
    "ratingsCount": 3,
    "readCount": 3,
    "reviewCount": 1,
    "goodreadsUrl": "https://www.goodreads.com/search?q=Animal+Farm+George+Orwell",
    "coverUrl": "",
  },
  {
    "id": "15",
    "title": "The Diary of a Young Girl",
    "authorId": "real_author_d35cd27084",
    "author": "Anne Frank",
    "genre": "Biography",
    "description": "Popular biography book by Anne Frank. Added to the catalog as real metadata for the recommendation web application.",
    "year": 1947,
    "averageRating": 4.4,
    "ratingsCount": 10,
    "readCount": 9,
    "reviewCount": 6,
    "goodreadsUrl": "https://www.goodreads.com/search?q=The+Diary+of+a+Young+Girl+Anne+Frank",
    "coverUrl": "",
  },
  {
    "id": "16",
    "title": "The Girl with the Dragon Tattoo",
    "authorId": "real_author_ef58043fd2",
    "author": "Stieg Larsson",
    "genre": "Thriller",
    "description": "Popular thriller book by Stieg Larsson. Added to the catalog as real metadata for the recommendation web application.",
    "year": 2005,
    "averageRating": 4.12,
    "ratingsCount": 8,
    "readCount": 5,
    "reviewCount": 6,
    "goodreadsUrl": "https://www.goodreads.com/search?q=The+Girl+with+the+Dragon+Tattoo+Stieg+Larsson",
    "coverUrl": "",
  },
]

export default tempBooks